### ISSUE TITLE
Allow Icon Importer to use a transparent color for background/foreground

### ISSUE THREAD

**Issue by Hydrall** [SvenWerlen/moulinette-gameicons#1]
Currently there's no way to do this, as there's naturally no hex code for "no color". Easiest seems to be just leaving it blank to be read as transparency, but there may be better options than that.

**Comment by SvenWerlen** [comment]
![image](https://user-images.githubusercontent.com/938060/117548351-8b64e300-b002-11eb-8858-1612078d6995.png)
It is now supported.
I implemented like you proposed (leave it blank). The color picker will show it as "black" but moulinette will handle it correctly.
