### ISSUE TITLE
Icons not showing in Icon window: Cert error

### ISSUE THREAD

**Issue by LorduFreeman** [SvenWerlen/moulinette-gameicons#2]
Getting `Failed to load resource: net::ERR_CERT_DATE_INVALID` when trying to search for game icons.

Foundry 0.8.8
DnD5e 1.4.1
Moulinette Core 3.4.0
Moulinette Icons 2.1.0

**Comment by SvenWerlen** [comment]
I think that their certificate expired and they forgot to renew it. It seems to be fixed. I cannot reproduce it.
